stages:
  - prepare
  - release
  - deployment

prepare_job:
  stage: prepare
  image: alpine:latest
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - apk add curl jq
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG" | jq -r .notes > release_notes.md'
    - 'curl -H "PRIVATE-TOKEN: $CI_API_TOKEN" -X POST "$CI_API_V4_URL/projects/$CI_PROJECT_ID/repository/changelog?version=$CI_COMMIT_TAG"'
  artifacts:
    paths:
    - release_notes.md

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
  - if: '$CI_COMMIT_TAG =~ /^v?\d+\.\d+\.\d+$/'
  script:
    - echo "Creating release"
  release:
    tag_name: "$CI_COMMIT_TAG"
    name: 'Release $CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    description: release_notes.md

deploy-job-non-prod:
  stage: deployment
  image: alpine
  environment:
    name: dynamic-env/$CI_COMMIT_REF_NAME
    url: https://${ENV_DOMAIN_NAME}
  before_script:
    - apk add curl
  script:
    - curl "${CI_ENVIRONMENT_URL}/admin/deploy.php?type=code&passphrase=${DEPLOY_KEY_PASS}&ci"
  rules:
    - if: $CI_COMMIT_REF_NAME == "staging"
    - if: $CI_COMMIT_REF_NAME == "saison-2"
