<?php

namespace App\Proxy\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Item extends \App\Entity\Item implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'cursed' => [parent::class, 'cursed', null],
        "\0".parent::class."\0".'element' => [parent::class, 'element', null],
        "\0".parent::class."\0".'enchanted' => [parent::class, 'enchanted', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'private' => [parent::class, 'private', null],
        "\0".parent::class."\0".'spell' => [parent::class, 'spell', null],
        "\0".parent::class."\0".'vorpal' => [parent::class, 'vorpal', null],
        'cursed' => [parent::class, 'cursed', null],
        'element' => [parent::class, 'element', null],
        'enchanted' => [parent::class, 'enchanted', null],
        'id' => [parent::class, 'id', null],
        'name' => [parent::class, 'name', null],
        'private' => [parent::class, 'private', null],
        'spell' => [parent::class, 'spell', null],
        'vorpal' => [parent::class, 'vorpal', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
