            CREATE TABLE craft_recipes (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, race_id INT DEFAULT NULL, INDEX IDX_26D39CCE6E59D40D (race_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8;
            CREATE TABLE craft_recipes_ingredients (id INT AUTO_INCREMENT NOT NULL, count INT DEFAULT 1 NOT NULL, recipe_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_3A88044F59D8A214 (recipe_id), INDEX IDX_3A88044F126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8;
            CREATE TABLE craft_recipes_results (id INT AUTO_INCREMENT NOT NULL, count INT DEFAULT 1 NOT NULL, recipe_id INT NOT NULL, item_id INT NOT NULL, INDEX IDX_7684F80159D8A214 (recipe_id), INDEX IDX_7684F801126F525E (item_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8;
            ALTER TABLE craft_recipes ADD CONSTRAINT FK_26D39CCE6E59D40D FOREIGN KEY (race_id) REFERENCES races (id);
            ALTER TABLE craft_recipes_ingredients ADD CONSTRAINT FK_3A88044F59D8A214 FOREIGN KEY (recipe_id) REFERENCES craft_recipes (id);
            ALTER TABLE craft_recipes_ingredients ADD CONSTRAINT FK_3A88044F126F525E FOREIGN KEY (item_id) REFERENCES items (id);
            ALTER TABLE craft_recipes_results ADD CONSTRAINT FK_7684F80159D8A214 FOREIGN KEY (recipe_id) REFERENCES craft_recipes (id);
            ALTER TABLE craft_recipes_results ADD CONSTRAINT FK_7684F801126F525E FOREIGN KEY (item_id) REFERENCES items (id);

