ALTER TABLE actions
ADD COLUMN category VARCHAR(50) DEFAULT NULL;
ADD COLUMN cost VARCHAR(50) DEFAULT NULL;
ADD COLUMN prerequisites VARCHAR(50) DEFAULT NULL;

ALTER TABLE action_passives
ADD COLUMN category VARCHAR(50) DEFAULT NULL;
ADD COLUMN prerequisites VARCHAR(50) DEFAULT NULL;

ALTER TABLE players_actions
DROP COLUMN charges;
