<?php

declare(strict_types=1);

namespace App\Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajout des passifs Apprenti I et Apprenti II dans la table action_passives.
 */
final class Version20260820120000_AddApprentiPassives extends AbstractMigration
{
    private const PASSIVES_DATA = [
        [
            'name'          => 'apprenti_i',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 1,
            'category'      => 'magic',
            'display_name'  => 'Apprenti I',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 1.',
            'prerequisites' => null,
        ],
        [
            'name'          => 'apprenti_ii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 1,
            'category'      => 'magic',
            'display_name'  => 'Apprenti II',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 1.',
            'prerequisites' => '{"need": ["apprenti_i"]}',
        ],
        [
            'name'          => 'apprenti_iii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 1,
            'category'      => 'magic',
            'display_name'  => 'Apprenti III',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 1.',
            'prerequisites' => '{"need": ["apprenti_ii"]}',
        ],
        [
            'name'          => 'apprenti_iv',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 1,
            'category'      => 'magic',
            'display_name'  => 'Apprenti IV',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 1.',
            'prerequisites' => '{"need": ["apprenti_iii"]}',
        ],
        [
            'name'          => 'apprenti_v',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 4.00,
            'level'         => 1,
            'category'      => 'magic',
            'display_name'  => 'Apprenti V',
            'text'          => 'Débloque 4 emplacements de sorts de niveau 1.',
            'prerequisites' => '{"need": ["apprenti_iv"]}',
        ],
        [
            'name'          => 'disciple_i',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 2,
            'category'      => 'magic',
            'display_name'  => 'Disciple I',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 2.',
            'prerequisites' => '{"need": ["apprenti_i"]}',
        ],
        [
            'name'          => 'disciple_ii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 2,
            'category'      => 'magic',
            'display_name'  => 'Disciple II',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 2.',
            'prerequisites' => '{"need": ["disciple_i"]}',
        ],
        [
            'name'          => 'disciple_iii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 2,
            'category'      => 'magic',
            'display_name'  => 'Disciple III',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 2.',
            'prerequisites' => '{"need": ["disciple_ii"]}',
        ],
        [
            'name'          => 'disciple_iv',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 2,
            'category'      => 'magic',
            'display_name'  => 'Disciple IV',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 2.',
            'prerequisites' => '{"need": ["disciple_iii"]}',
        ],
        [
            'name'          => 'disciple_v',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 4.00,
            'level'         => 2,
            'category'      => 'magic',
            'display_name'  => 'Disciple V',
            'text'          => 'Débloque 4 emplacements de sorts de niveau 2.',
            'prerequisites' => '{"need": ["disciple_iv"]}',
        ],
        [
            'name'          => 'mage_i',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 3,
            'category'      => 'magic',
            'display_name'  => 'Mage I',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 3.',
            'prerequisites' => '{"need": ["disciple_i"]}',
        ],
        [
            'name'          => 'mage_ii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 3,
            'category'      => 'magic',
            'display_name'  => 'Mage II',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 3.',
            'prerequisites' => '{"need": ["mage_i"]}',
        ],
        [
            'name'          => 'mage_iii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 3,
            'category'      => 'magic',
            'display_name'  => 'Mage III',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 3.',
            'prerequisites' => '{"need": ["mage_ii"]}',
        ],
        [
            'name'          => 'mage_iv',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 3,
            'category'      => 'magic',
            'display_name'  => 'Mage IV',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 3.',
            'prerequisites' => '{"need": ["mage_iii"]}',
        ],
        [
            'name'          => 'mage_v',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 4.00,
            'level'         => 3,
            'category'      => 'magic',
            'display_name'  => 'Mage V',
            'text'          => 'Débloque 4 emplacements de sorts de niveau 3.',
            'prerequisites' => '{"need": ["mage_iv"]}',
        ],
        [
            'name'          => 'grand_mage_i',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 2.00,
            'level'         => 4,
            'category'      => 'magic',
            'display_name'  => 'Grand Mage I',
            'text'          => 'Débloque 2 emplacements de sorts de niveau 4.',
            'prerequisites' => '{"need": ["mage_i"]}',
        ],
        [
            'name'          => 'grand_mage_ii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 2.00,
            'level'         => 4,
            'category'      => 'magic',
            'display_name'  => 'Grand Mage II',
            'text'          => 'Débloque 2 emplacements de sorts de niveau 4.',
            'prerequisites' => '{"need": ["grand_mage_i"]}',
        ],
        [
            'name'          => 'grand_mage_iii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 2.00,
            'level'         => 4,
            'category'      => 'magic',
            'display_name'  => 'Grand Mage III',
            'text'          => 'Débloque 2 emplacements de sorts de niveau 4.',
            'prerequisites' => '{"need": ["grand_mage_ii"]}',
        ],
        [
            'name'          => 'grand_mage_iv',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 2.00,
            'level'         => 4,
            'category'      => 'magic',
            'display_name'  => 'Grand Mage IV',
            'text'          => 'Débloque 2 emplacements de sorts de niveau 4.',
            'prerequisites' => '{"need": ["grand_mage_iii"]}',
        ],
        [
            'name'          => 'grand_mage_v',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 3.00,
            'level'         => 4,
            'category'      => 'magic',
            'display_name'  => 'Grand Mage V',
            'text'          => 'Débloque 3 emplacements de sorts de niveau 4.',
            'prerequisites' => '{"need": ["grand_mage_iv"]}',
        ],
        [
            'name'          => 'archimage_i',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 1.00,
            'level'         => 5,
            'category'      => 'magic',
            'display_name'  => 'Archimage I',
            'text'          => 'Débloque 1 emplacement de sorts de niveau 5.',
            'prerequisites' => '{"need": ["grand_mage_i"]}',
        ],
        [
            'name'          => 'archimage_ii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 1.00,
            'level'         => 5,
            'category'      => 'magic',
            'display_name'  => 'Archimage II',
            'text'          => 'Débloque 1 emplacement de sorts de niveau 5.',
            'prerequisites' => '{"need": ["grand_mage_i"]}',
        ],
        [
            'name'          => 'archimage_iii',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 1.00,
            'level'         => 5,
            'category'      => 'magic',
            'display_name'  => 'Archimage III',
            'text'          => 'Débloque 1 emplacement de sorts de niveau 5.',
            'prerequisites' => '{"need": ["grand_mage_ii"]}',
        ],
        [
            'name'          => 'archimage_iv',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 1.00,
            'level'         => 5,
            'category'      => 'magic',
            'display_name'  => 'Archimage IV',
            'text'          => 'Débloque 1 emplacement de sorts de niveau 5.',
            'prerequisites' => '{"need": ["grand_mage_iii"]}',
        ],
        [
            'name'          => 'archimage_v',
            'traits'        => '[]',
            'type'          => 'spell-slot',
            'carac'         => 0,
            'value'         => 2.00,
            'level'         => 5,
            'category'      => 'magic',
            'display_name'  => 'Archimage V',
            'text'          => 'Débloque 2 emplacement de sorts de niveau 5.',
            'prerequisites' => '{"need": ["grand_mage_iv"]}',
        ],
    ];

    public function getDescription(): string
    {
        return 'Ajout des passifs d\'emplacements de sorts dans action_passives';
    }

    public function up(Schema $schema): void
    {
        foreach (self::PASSIVES_DATA as $passive) {
            $this->addSql(
                'INSERT INTO action_passives (name, traits, type, carac, value, level, category, display_name, text, prerequisites) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)',
                array_values($passive)
            );
        }
    }

    public function down(Schema $schema): void
    {
        $names = array_column(self::PASSIVES_DATA, 'name');
        $placeholders = implode(', ', array_fill(0, count($names), '?'));

        $this->addSql(
            "DELETE FROM action_passives WHERE name IN ($placeholders)",
            $names
        );
    }
}