<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ActionPassive extends \App\Entity\ActionPassive implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'carac' => [parent::class, 'carac', null],
        "\0".parent::class."\0".'conditions' => [parent::class, 'conditions', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'level' => [parent::class, 'level', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'race' => [parent::class, 'race', null],
        "\0".parent::class."\0".'traits' => [parent::class, 'traits', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        "\0".parent::class."\0".'value' => [parent::class, 'value', null],
        'carac' => [parent::class, 'carac', null],
        'conditions' => [parent::class, 'conditions', null],
        'id' => [parent::class, 'id', null],
        'level' => [parent::class, 'level', null],
        'name' => [parent::class, 'name', null],
        'race' => [parent::class, 'race', null],
        'traits' => [parent::class, 'traits', null],
        'type' => [parent::class, 'type', null],
        'value' => [parent::class, 'value', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
